import { VARSAYILAN_DIL, type Dil } from "./diller";

/**
 * Müşteri ekranlarının metin sözlüğü.
 *
 * Türkçe sözlük anahtar kümesini belirliyor; diğer diller aynı tipte
 * olduğu için yeni bir metin eklendiğinde hepsini doldurmadan derleme
 * geçmiyor. Eksik çeviri, ekranda yarı Türkçe bir arayüzden daha erken
 * fark edilsin istiyoruz.
 *
 * {süslü} yer tutucular `cevir`in ikinci argümanıyla doldurulur.
 */

const tr = {
  // --- ortak
  "dil.sec": "Dil",
  "ortak.masa": "Masa {no}",
  "ortak.giris": "Giriş",
  "ortak.hosGeldiniz": "Hoş geldiniz",
  "ortak.menu": "Menü",
  "ortak.kapat": "Kapat",
  "ortak.istegeBagli": "(isteğe bağlı)",

  // --- karşılama ekranı
  "karsilama.menuBaslik": "Menüyü görüntüle",
  "karsilama.menuAciklama": "Fotoğraflı menü, fiyatlar ve günün durumu",
  "karsilama.anketBaslik": "Deneyiminizi değerlendirin",
  "karsilama.anketAciklama": "30 saniyenizi alır",
  "karsilama.dipnot": "Görüşleriniz doğrudan işletme sahibine ulaşır.",
  "duyurular.baslik": "Duyurular",
  "duyurular.geriDon": "← Geri",
  "duyurular.bosDurum": "Şu an aktif duyuru yok.",
  "siparis.baslik": "Online sipariş",
  "menu.fiyatGuncelleme": "Fiyatlar {tarih} tarihinde güncellendi.",

  // --- Instagram / Wi-Fi
  "iletisim.instagram": "Instagram",
  "iletisim.wifiButon": "Wi-Fi bilgisi",
  "iletisim.wifiAgi": "Wi-Fi ağı",
  "iletisim.wifiSifre": "Şifre",
  "iletisim.kopyala": "Kopyala",
  "iletisim.kopyalandi": "Kopyalandı",

  // --- menü
  "menu.ara": "Menüde ara…",
  "menu.aramaEtiket": "Menüde ara",
  "menu.filtreler": "Diyet ve alerjen filtreleri",
  "menu.bolumler": "Menü bölümleri",
  "menu.tumBolumler": "Menü",
  "menu.urunAdedi": "{adet} ürün",
  "menu.sonucSayisi": "{adet} ürün bulundu",
  "menu.temizle": "Temizle",
  "menu.aramaBos": "“{terim}” için bir sonuç bulunamadı.",
  "menu.filtreBos": "Seçili filtrelere uyan ürün yok.",
  "menu.bugunYok": "Bugün yok",
  "menu.ayrinti": "{ad} — ayrıntıları gör",
  "menu.secimEkle": "{ad} — değerlendirmeye ekle",
  "menu.fiyat": "Fiyat",
  "menu.anketKisayolBaslik": "Deneyiminizi değerlendirin",
  "menu.anketKisayolAciklama": "Yediklerinizi tek tek puanlayabilirsiniz",
  "menu.kdv": "Fiyatlara KDV dahildir. Menü içeriği işletme tarafından güncellenir.",
  "menu.sikayetOneri": "Şikayet & Öneri",
  "menu.secimAltBaslik": "Aldıklarınızı seçin",
  "menu.secimBaslik": "Ne aldınız?",
  "menu.secimAciklama":
    "Yediklerinize dokunup işaretleyin, sonra aşağıdan değerlendirmeye ekleyin.",
  "menu.secilenSayisi": "{adet} ürün seçildi",
  "menu.secimYok": "Henüz seçim yok",
  "menu.secimTamamla": "Değerlendirmeye ekle",
  "menu.secimBos": "Değerlendirmeye dön",
  "menu.secimdenCikar": "Seçimden çıkar",

  // --- menü etiketleri
  "etiket.vegan": "Vegan",
  "etiket.vejetaryen": "Vejetaryen",
  "etiket.glutensiz": "Glutensiz",
  "etiket.laktozsuz": "Laktozsuz",
  "etiket.aci": "Acı",
  "etiket.yeni": "Yeni",
  "etiket.populer": "Popüler",

  // --- yıldızlar
  "yildiz.1": "Çok kötü",
  "yildiz.2": "Kötü",
  "yildiz.3": "İdare eder",
  "yildiz.4": "İyi",
  "yildiz.5": "Harika",
  "yildiz.etiket": "{sayi} yıldız — {ad}",
  "yildiz.genel": "Genel memnuniyet puanı",
  "yildiz.kategori": "{ad} puanı",

  // --- anket
  "anket.baslik": "Deneyiminizi nasıl buldunuz?",
  "anket.menuyeDon": "Menüye dön",
  "anket.ipucu": "Puan vermek için bir yıldıza dokunun",
  "anket.altBilgi1": "Görüşünüz doğrudan {ad} sorumlusuna iletilir.",
  "anket.altBilgi2": "Ad soyad sorulmaz, isim vermek zorunda değilsiniz.",
  "anket.detaylar": "Detaylar",
  "anket.detayIpucu": "İstediğinizi boş bırakabilirsiniz.",
  "anket.sorunSoru": "Hangi konuda sorun yaşadınız?",
  "anket.yorumBaslik": "Eklemek istediğiniz bir şey var mı?",
  "anket.yorumDusuk": "Ne iyi gitmedi? Yazarsanız düzeltebiliriz.",
  "anket.yorumYuksek": "Beğendiğiniz veya eksik bulduğunuz şeyler...",
  "anket.fotoBaslik": "Fotoğraf eklemek ister misiniz? (isteğe bağlı)",
  "anket.fotoIpucu": "Yalnızca işletme sorumlusu görür.",
  "anket.iletisimBaslik": "Size dönmemizi ister misiniz?",
  "anket.iletisimDusuk": "Bırakırsanız işletme sorumlusu sizinle bizzat ilgilenir.",
  "anket.iletisimYuksek": "Sadece bu geri bildiriminiz için ararız.",
  "anket.iletisimKampanyaBaslik": "Kampanyalardan haberdar olmak ister misiniz?",
  "anket.iletisimKampanyaMetin":
    "Bilgilerinizi bırakırsanız yeni ürün ve kampanyalarımızı ilk siz duyarsınız.",
  "anket.iletisimKanali": "İletişim kanalı",
  "anket.telefon": "Telefon",
  "anket.eposta": "E-posta",
  "anket.telefonOrnek": "05XX XXX XX XX",
  "anket.epostaOrnek": "ornek@eposta.com",
  "anket.gonder": "Gönder",
  "anket.gonderiliyor": "Gönderiliyor…",
  "anket.googleButon": "Google'da Değerlendir",
  "anket.puanGerekli": "Lütfen önce genel memnuniyet puanınızı verin.",
  "anket.besYildizBaslik": "Bizi 5 yıldızla değerlendirdiniz, teşekkürler! 🎉",
  "anket.besYildizMetin":
    "Google'da da birkaç saniyenizi ayırıp yorum bırakır mısınız? Aşağıdaki adım tamamen isteğe bağlı.",
  "anket.rizaGerekli": "İletişim bilgisi bırakmak için aydınlatma metnini onaylayın.",

  // --- ürün puanlama adımı
  "urun.baslik": "Ne aldınız?",
  "urun.aciklama": "Seçtiklerinizi ayrı ayrı puanlayabilirsiniz. İsteğe bağlı.",
  "urun.menudenSec": "Menüden seç",
  "urun.menudenSecAciklama": "Fotoğraflı menüden işaretleyip buraya dönün",
  "urun.ara": "Ürün ara...",
  "urun.bulunamadi": "Bu isimde ürün yok. Menüden seçerek de işaretleyebilirsiniz.",
  "urun.tumunuGoster": "Tüm ürünleri göster ({adet})",

  // --- teşekkür ekranları
  "tesekkur.googleBaslik": "Çok teşekkürler! 🎉",
  "tesekkur.googleMetin":
    "Beğendiğinize sevindik. Bu deneyimi Google’da da paylaşırsanız bizim için çok değerli olur — 30 saniyenizi almaz.",
  "tesekkur.googleButon": "Google’da yorum bırak",
  "tesekkur.googleAtla": "İsterseniz bu adımı atlayabilirsiniz.",
  "tesekkur.icBaslik": "Geri bildiriminiz için teşekkürler",
  "tesekkur.icMetin":
    "Yazdıklarınız doğrudan işletme sorumlusuna iletildi. Eksiğimizi söylediğiniz için teşekkür ederiz — en kısa sürede ilgileneceğiz.",

  // --- KVKK
  "kvkk.ozet":
    "Aydınlatma metnini okudum. İletişim bilgisi bırakırsam {ad} ile paylaşılmasına ve yalnızca bu geri bildirim hakkında bana dönülmek üzere {gun} gün saklanmasına açık rıza veriyorum.",
  "kvkk.baslik": "Kişisel verilerin korunması hakkında bilgilendirme",
  "kvkk.sorumluBaslik": "Veri sorumlusu",
  "kvkk.veriBaslik": "Hangi veriyi alıyoruz",
  "kvkk.veriMetin":
    "Verdiğiniz puanlar ve yorumunuz. İsterseniz size dönebilmemiz için bıraktığınız telefon numarası veya e-posta adresi. Adınızı sormuyoruz.",
  "kvkk.amacBaslik": "Niçin",
  "kvkk.amacMetin":
    "Puan ve yorumlar hizmet kalitemizi ölçmek için; iletişim bilgisi yalnızca bu geri bildirim hakkında size dönüş yapmak için kullanılır. Pazarlama amacıyla kullanılmaz, üçüncü kişilerle paylaşılmaz.",
  "kvkk.dayanakBaslik": "Hukuki dayanak",
  "kvkk.dayanakMetin":
    "Puan ve yorumlar, hizmetimizi geliştirmeye yönelik meşru menfaatimiz kapsamında işlenir. İletişim bilgisi yalnızca açık rızanızla saklanır — boş bırakırsanız geri bildiriminiz yine kaydedilir.",
  "kvkk.sureBaslik": "Ne kadar süreyle",
  "kvkk.sureMetin":
    "İletişim bilgisi en fazla {gun} gün saklanır ve sonra otomatik olarak silinir. Puan ve yorumlar, kimliğinizle ilişkilendirilmeden istatistik amacıyla saklanmaya devam eder.",
  "kvkk.haklarBaslik": "Haklarınız",
  "kvkk.haklarMetin":
    "Verilerinize erişme, düzeltilmesini veya silinmesini isteme ve rızanızı geri alma hakkınız var. Bunun için işletmeye başvurmanız yeterli; iletişim bilginiz talebiniz üzerine derhal silinir.",
  /** Türkçe dışındaki dillerde gösterilen "asıl metin Türkçedir" notu. */
  "kvkk.asilDil": "",

  // --- görsel yükleme (ankette müşteriye de görünür)
  // --- varsayılan sorun seçenekleri (düşük puanda açılan liste)
  "secenek.tuvaletler": "Tuvaletler",
  "secenek.masalar": "Masalar",
  "secenek.zemin": "Zemin",
  "secenek.catalBicak": "Çatal-bıçak",
  "secenek.bardaklar": "Bardaklar",
  "secenek.cokBeklettiler": "Çok beklettiler",
  "secenek.ilgisizdi": "İlgisizdi",
  "secenek.siparisYanlis": "Sipariş yanlış geldi",
  "secenek.uslupKotu": "Üslup kötüydü",
  "secenek.soguktu": "Soğuktu",
  "secenek.tuzBaharat": "Tuzu/baharatı",
  "secenek.porsiyonKucuk": "Porsiyon küçüktü",
  "secenek.tazelik": "Tazelik",
  "secenek.sunum": "Sunum",
  "secenek.siparisAlinmasi": "Sipariş alınması",
  "secenek.yemeginGelmesi": "Yemeğin gelmesi",
  "secenek.hesapOdemesi": "Hesap ödemesi",
  "secenek.porsiyonaGorePahali": "Porsiyona göre pahalı",
  "secenek.menuFiyatFarkli": "Menüdeki fiyat farklıydı",
  "secenek.servisUcreti": "Servis ücreti",
  "secenek.gurultu": "Gürültü",
  "secenek.muzikSesi": "Müzik sesi",
  "secenek.isiHavalandirma": "Isı/havalandırma",
  "secenek.aydinlatma": "Aydınlatma",
  "secenek.koltuklar": "Koltuklar",
  "secenek.tabakDuzeni": "Tabak düzeni",
  "secenek.sicaklik": "Sıcaklık",
  "secenek.porsiyonGorunumu": "Porsiyon görünümü",
  "secenek.temizlik": "Temizlik",
  "secenek.kagitSabunYok": "Kağıt/sabun yok",
  "secenek.koku": "Koku",
  "secenek.siraBekledim": "Sıra bekledim",
  "secenek.yerYoktu": "Yer yoktu",
  "secenek.uzunBekledim": "Uzun bekledim",
  "secenek.ucret": "Ücret",
  "gorsel.sec": "Görsel seç",
  "gorsel.degistir": "Değiştir",
  "gorsel.kaldir": "Kaldır",
  "gorsel.isleniyor": "İşleniyor…",
  "gorsel.hataTur": "Lütfen bir görsel dosyası seçin.",
  "gorsel.hataIsleme": "Görsel işlenemedi. Başka bir dosya deneyin.",
  "gorsel.hataBoyut": "Dosya çok büyük (en fazla {boyut}). Daha küçük bir görsel deneyin.",
  // --- ticari ileti (İYS)
  "iys.metin":
    "{ad} markası adına, bıraktığım iletişim adresine {kanal} yoluyla kampanya, indirim ve duyuru içeren ticari elektronik ileti gönderilmesine izin veriyorum. Bu izni dilediğim zaman ücretsiz olarak geri alabilirim.",
  "iys.ipucu": "İsteğe bağlı. İşaretlemeseniz de geri bildiriminiz kaydedilir.",
  "iys.metniOku": "Aydınlatma metnini oku",
  "iys.sms": "SMS",
  "iys.eposta": "e-posta",
} as const;

export type MetinAnahtari = keyof typeof tr;

/** Sözlükteki tüm anahtarlar — testler eksik çeviriyi buradan tarıyor. */
export const TUM_ANAHTARLAR = Object.keys(tr) as MetinAnahtari[];
type Sozluk = Record<MetinAnahtari, string>;

const en: Sozluk = {
  "dil.sec": "Language",
  "ortak.masa": "Table {no}",
  "ortak.giris": "Entrance",
  "ortak.hosGeldiniz": "Welcome",
  "ortak.menu": "Menu",
  "ortak.kapat": "Close",
  "ortak.istegeBagli": "(optional)",

  "karsilama.menuBaslik": "View the menu",
  "karsilama.menuAciklama": "Photos, prices and what’s available today",
  "karsilama.anketBaslik": "Rate your experience",
  "karsilama.anketAciklama": "Takes 30 seconds",
  "karsilama.dipnot": "Your feedback goes straight to the owner.",
  "duyurular.baslik": "Announcements",
  "duyurular.geriDon": "← Back",
  "duyurular.bosDurum": "No active announcements right now.",
  "siparis.baslik": "Order online",
  "menu.fiyatGuncelleme": "Prices last updated on {tarih}.",

  "iletisim.instagram": "Instagram",
  "iletisim.wifiButon": "Wi-Fi details",
  "iletisim.wifiAgi": "Wi-Fi network",
  "iletisim.wifiSifre": "Password",
  "iletisim.kopyala": "Copy",
  "iletisim.kopyalandi": "Copied",

  "menu.ara": "Search the menu…",
  "menu.aramaEtiket": "Search the menu",
  "menu.filtreler": "Dietary and allergen filters",
  "menu.bolumler": "Menu sections",
  "menu.tumBolumler": "Menu",
  "menu.urunAdedi": "{adet} items",
  "menu.sonucSayisi": "{adet} items found",
  "menu.temizle": "Clear",
  "menu.aramaBos": "No results for “{terim}”.",
  "menu.filtreBos": "No items match the selected filters.",
  "menu.bugunYok": "Sold out",
  "menu.ayrinti": "{ad} — view details",
  "menu.secimEkle": "{ad} — add to your review",
  "menu.fiyat": "Price",
  "menu.anketKisayolBaslik": "Rate your experience",
  "menu.anketKisayolAciklama": "You can rate each dish separately",
  "menu.kdv": "Prices include VAT. The menu is maintained by the venue.",
  "menu.sikayetOneri": "Feedback & Suggestions",
  "menu.secimAltBaslik": "Pick what you had",
  "menu.secimBaslik": "What did you have?",
  "menu.secimAciklama": "Tap what you ate, then add it to your review below.",
  "menu.secilenSayisi": "{adet} items selected",
  "menu.secimYok": "Nothing selected yet",
  "menu.secimTamamla": "Add to review",
  "menu.secimBos": "Back to review",
  "menu.secimdenCikar": "Remove from selection",

  "etiket.vegan": "Vegan",
  "etiket.vejetaryen": "Vegetarian",
  "etiket.glutensiz": "Gluten free",
  "etiket.laktozsuz": "Lactose free",
  "etiket.aci": "Spicy",
  "etiket.yeni": "New",
  "etiket.populer": "Popular",

  "yildiz.1": "Very poor",
  "yildiz.2": "Poor",
  "yildiz.3": "Okay",
  "yildiz.4": "Good",
  "yildiz.5": "Excellent",
  "yildiz.etiket": "{sayi} stars — {ad}",
  "yildiz.genel": "Overall rating",
  "yildiz.kategori": "{ad} rating",

  "anket.baslik": "How was your experience?",
  "anket.menuyeDon": "Back to menu",
  "anket.ipucu": "Tap a star to rate",
  "anket.altBilgi1": "Your feedback goes straight to the {ad} manager.",
  "anket.altBilgi2": "We don’t ask for your name — staying anonymous is fine.",
  "anket.detaylar": "Details",
  "anket.detayIpucu": "Feel free to skip any of these.",
  "anket.sorunSoru": "What exactly went wrong?",
  "anket.yorumBaslik": "Anything you’d like to add?",
  "anket.yorumDusuk": "What went wrong? Tell us and we can fix it.",
  "anket.yorumYuksek": "What you liked, or what we could do better...",
  "anket.fotoBaslik": "Would you like to add a photo? (optional)",
  "anket.fotoIpucu": "Only the venue manager sees it.",
  "anket.iletisimBaslik": "Would you like us to get back to you?",
  "anket.iletisimDusuk": "Leave a contact and the manager will follow up personally.",
  "anket.iletisimYuksek": "We’ll only contact you about this feedback.",
  "anket.iletisimKampanyaBaslik": "Want to hear about our campaigns?",
  "anket.iletisimKampanyaMetin":
    "Leave your details and you’ll be the first to know about new items and offers.",
  "anket.iletisimKanali": "Contact method",
  "anket.telefon": "Phone",
  "anket.eposta": "Email",
  "anket.telefonOrnek": "05XX XXX XX XX",
  "anket.epostaOrnek": "name@example.com",
  "anket.gonder": "Send",
  "anket.gonderiliyor": "Sending…",
  "anket.googleButon": "Review on Google",
  "anket.puanGerekli": "Please give an overall rating first.",
  "anket.besYildizBaslik": "You rated us 5 stars, thank you! 🎉",
  "anket.besYildizMetin":
    "Would you take a few seconds to leave a review on Google too? The step below is entirely optional.",
  "anket.rizaGerekli": "To leave contact details, please accept the privacy notice.",

  "urun.baslik": "What did you have?",
  "urun.aciklama": "You can rate each item separately. Optional.",
  "urun.menudenSec": "Pick from the menu",
  "urun.menudenSecAciklama": "Choose from the photo menu and come back here",
  "urun.ara": "Search items...",
  "urun.bulunamadi": "No item with that name. You can also pick from the menu.",
  "urun.tumunuGoster": "Show all items ({adet})",

  "tesekkur.googleBaslik": "Thank you! 🎉",
  "tesekkur.googleMetin":
    "We’re glad you enjoyed it. Sharing this on Google would mean a lot to us — it takes 30 seconds.",
  "tesekkur.googleButon": "Review us on Google",
  "tesekkur.googleAtla": "You can skip this step if you prefer.",
  "tesekkur.icBaslik": "Thank you for your feedback",
  "tesekkur.icMetin":
    "Your message went straight to the venue manager. Thank you for telling us what fell short — we’ll look into it right away.",

  "kvkk.ozet":
    "I have read the privacy notice. If I leave contact details, I consent to them being shared with {ad} and kept for {gun} days solely to respond to this feedback.",
  "kvkk.baslik": "Personal data protection notice",
  "kvkk.sorumluBaslik": "Data controller",
  "kvkk.veriBaslik": "What we collect",
  "kvkk.veriMetin":
    "The ratings and comment you give. Optionally, the phone number or email address you leave so we can get back to you. We do not ask for your name.",
  "kvkk.amacBaslik": "Why",
  "kvkk.amacMetin":
    "Ratings and comments are used to measure our service quality; contact details are used only to respond to this feedback. They are not used for marketing and not shared with third parties.",
  "kvkk.dayanakBaslik": "Legal basis",
  "kvkk.dayanakMetin":
    "Ratings and comments are processed under our legitimate interest in improving our service. Contact details are stored only with your explicit consent — if you leave them blank, your feedback is still recorded.",
  "kvkk.sureBaslik": "Retention",
  "kvkk.sureMetin":
    "Contact details are kept for at most {gun} days and then deleted automatically. Ratings and comments continue to be kept for statistics, unlinked from your identity.",
  "kvkk.haklarBaslik": "Your rights",
  "kvkk.haklarMetin":
    "You may access your data, ask for it to be corrected or deleted, and withdraw your consent. Just contact the venue; your contact details are deleted immediately on request.",
  "kvkk.asilDil":
    "This is a courtesy translation. The Turkish version is the legally binding text.",

  "secenek.tuvaletler": "Restrooms",
  "secenek.masalar": "Tables",
  "secenek.zemin": "Floor",
  "secenek.catalBicak": "Cutlery",
  "secenek.bardaklar": "Glassware",
  "secenek.cokBeklettiler": "Long wait",
  "secenek.ilgisizdi": "Inattentive",
  "secenek.siparisYanlis": "Wrong order",
  "secenek.uslupKotu": "Rude manner",
  "secenek.soguktu": "Served cold",
  "secenek.tuzBaharat": "Seasoning",
  "secenek.porsiyonKucuk": "Small portion",
  "secenek.tazelik": "Freshness",
  "secenek.sunum": "Presentation",
  "secenek.siparisAlinmasi": "Taking the order",
  "secenek.yemeginGelmesi": "Food arriving",
  "secenek.hesapOdemesi": "Paying the bill",
  "secenek.porsiyonaGorePahali": "Pricey for the portion",
  "secenek.menuFiyatFarkli": "Price differed from menu",
  "secenek.servisUcreti": "Service charge",
  "secenek.gurultu": "Noise",
  "secenek.muzikSesi": "Music volume",
  "secenek.isiHavalandirma": "Temperature/airflow",
  "secenek.aydinlatma": "Lighting",
  "secenek.koltuklar": "Seating",
  "secenek.tabakDuzeni": "Plating",
  "secenek.sicaklik": "Temperature",
  "secenek.porsiyonGorunumu": "Portion look",
  "secenek.temizlik": "Cleanliness",
  "secenek.kagitSabunYok": "No paper/soap",
  "secenek.koku": "Odour",
  "secenek.siraBekledim": "Had to queue",
  "secenek.yerYoktu": "No space",
  "secenek.uzunBekledim": "Long wait",
  "secenek.ucret": "Cost",
  "gorsel.sec": "Choose a photo",
  "gorsel.degistir": "Change",
  "gorsel.kaldir": "Remove",
  "gorsel.isleniyor": "Processing…",
  "gorsel.hataTur": "Please choose an image file.",
  "gorsel.hataIsleme": "The image could not be processed. Try another file.",
  "gorsel.hataBoyut": "File is too large (max {boyut}). Try a smaller image.",
  "iys.metin":
    "I consent to receiving commercial electronic messages with campaigns, discounts and announcements from {ad} via {kanal} at the contact address I provided. I may withdraw this consent free of charge at any time.",
  "iys.ipucu": "Optional. Your feedback is recorded either way.",
  "iys.metniOku": "Read the privacy notice",
  "iys.sms": "SMS",
  "iys.eposta": "email",
};

const ar: Sozluk = {
  "dil.sec": "اللغة",
  "ortak.masa": "طاولة {no}",
  "ortak.giris": "المدخل",
  "ortak.hosGeldiniz": "أهلاً بك",
  "ortak.menu": "القائمة",
  "ortak.kapat": "إغلاق",
  "ortak.istegeBagli": "(اختياري)",

  "karsilama.menuBaslik": "عرض القائمة",
  "karsilama.menuAciklama": "صور وأسعار والمتوفر اليوم",
  "karsilama.anketBaslik": "قيّم تجربتك",
  "karsilama.anketAciklama": "يستغرق ٣٠ ثانية",
  "karsilama.dipnot": "ملاحظاتك تصل مباشرة إلى صاحب المكان.",
  "duyurular.baslik": "الإعلانات",
  "duyurular.geriDon": "← رجوع",
  "duyurular.bosDurum": "لا توجد إعلانات نشطة حاليًا.",
  "siparis.baslik": "الطلب عبر الإنترنت",
  "menu.fiyatGuncelleme": "آخر تحديث للأسعار بتاريخ {tarih}.",

  "iletisim.instagram": "إنستغرام",
  "iletisim.wifiButon": "معلومات الواي فاي",
  "iletisim.wifiAgi": "شبكة الواي فاي",
  "iletisim.wifiSifre": "كلمة المرور",
  "iletisim.kopyala": "نسخ",
  "iletisim.kopyalandi": "تم النسخ",

  "menu.ara": "ابحث في القائمة…",
  "menu.aramaEtiket": "ابحث في القائمة",
  "menu.filtreler": "عوامل تصفية الحمية والحساسية",
  "menu.bolumler": "أقسام القائمة",
  "menu.tumBolumler": "القائمة",
  "menu.urunAdedi": "{adet} عنصر",
  "menu.sonucSayisi": "تم العثور على {adet} صنف",
  "menu.temizle": "مسح",
  "menu.aramaBos": "لا نتائج لـ «{terim}».",
  "menu.filtreBos": "لا يوجد صنف يطابق عوامل التصفية المختارة.",
  "menu.bugunYok": "غير متوفر",
  "menu.ayrinti": "{ad} — عرض التفاصيل",
  "menu.secimEkle": "{ad} — أضف إلى تقييمك",
  "menu.fiyat": "السعر",
  "menu.anketKisayolBaslik": "قيّم تجربتك",
  "menu.anketKisayolAciklama": "يمكنك تقييم كل صنف على حدة",
  "menu.kdv": "الأسعار شاملة الضريبة. المكان مسؤول عن تحديث القائمة.",
  "menu.sikayetOneri": "شكوى واقتراح",
  "menu.secimAltBaslik": "اختر ما تناولته",
  "menu.secimBaslik": "ماذا تناولت؟",
  "menu.secimAciklama": "اختر ما تناولته ثم أضفه إلى تقييمك بالأسفل.",
  "menu.secilenSayisi": "تم اختيار {adet} صنف",
  "menu.secimYok": "لم تختر شيئاً بعد",
  "menu.secimTamamla": "أضف إلى التقييم",
  "menu.secimBos": "العودة إلى التقييم",
  "menu.secimdenCikar": "إزالة من الاختيار",

  "etiket.vegan": "نباتي صرف",
  "etiket.vejetaryen": "نباتي",
  "etiket.glutensiz": "خالٍ من الغلوتين",
  "etiket.laktozsuz": "خالٍ من اللاكتوز",
  "etiket.aci": "حار",
  "etiket.yeni": "جديد",
  "etiket.populer": "الأكثر طلباً",

  "yildiz.1": "سيئ جداً",
  "yildiz.2": "سيئ",
  "yildiz.3": "مقبول",
  "yildiz.4": "جيد",
  "yildiz.5": "ممتاز",
  "yildiz.etiket": "{sayi} نجوم — {ad}",
  "yildiz.genel": "التقييم العام",
  "yildiz.kategori": "تقييم {ad}",

  "anket.baslik": "كيف كانت تجربتك؟",
  "anket.menuyeDon": "العودة إلى القائمة",
  "anket.ipucu": "اضغط على نجمة للتقييم",
  "anket.altBilgi1": "ملاحظاتك تصل مباشرة إلى مسؤول {ad}.",
  "anket.altBilgi2": "لا نطلب اسمك، ويمكنك البقاء مجهولاً.",
  "anket.detaylar": "التفاصيل",
  "anket.detayIpucu": "يمكنك ترك أي منها فارغاً.",
  "anket.sorunSoru": "ما المشكلة التي واجهتها تحديداً؟",
  "anket.yorumBaslik": "هل تود إضافة شيء؟",
  "anket.yorumDusuk": "ما الذي لم يكن جيداً؟ أخبرنا لنصلحه.",
  "anket.yorumYuksek": "ما أعجبك أو ما يمكننا تحسينه...",
  "anket.fotoBaslik": "هل تود إضافة صورة؟ (اختياري)",
  "anket.fotoIpucu": "يراها مسؤول المكان فقط.",
  "anket.iletisimBaslik": "هل تود أن نتواصل معك؟",
  "anket.iletisimDusuk": "اترك وسيلة تواصل وسيتابع المسؤول الأمر بنفسه.",
  "anket.iletisimYuksek": "سنتواصل معك بخصوص هذه الملاحظة فقط.",
  "anket.iletisimKampanyaBaslik": "هل تود معرفة عروضنا؟",
  "anket.iletisimKampanyaMetin":
    "اترك بياناتك لتكون أول من يعرف بالمنتجات والعروض الجديدة.",
  "anket.iletisimKanali": "وسيلة التواصل",
  "anket.telefon": "الهاتف",
  "anket.eposta": "البريد الإلكتروني",
  "anket.telefonOrnek": "05XX XXX XX XX",
  "anket.epostaOrnek": "name@example.com",
  "anket.gonder": "إرسال",
  "anket.gonderiliyor": "جارٍ الإرسال…",
  "anket.googleButon": "قيّمنا على Google",
  "anket.puanGerekli": "يرجى إعطاء التقييم العام أولاً.",
  "anket.besYildizBaslik": "قيّمتنا بـ 5 نجوم، شكرًا لك! 🎉",
  "anket.besYildizMetin":
    "هل يمكنك تخصيص بضع ثوانٍ لترك تقييم على جوجل أيضًا؟ قبل ذلك، يمكنك ترك معلومات التواصل الخاصة بك إذا أردت حتى نتمكن من الوصول إليك.",
  "anket.rizaGerekli": "لترك بيانات التواصل، يرجى الموافقة على إشعار الخصوصية.",

  "urun.baslik": "ماذا تناولت؟",
  "urun.aciklama": "يمكنك تقييم كل صنف على حدة. اختياري.",
  "urun.menudenSec": "اختر من القائمة",
  "urun.menudenSecAciklama": "اختر من القائمة المصورة ثم عد إلى هنا",
  "urun.ara": "ابحث عن صنف...",
  "urun.bulunamadi": "لا يوجد صنف بهذا الاسم. يمكنك الاختيار من القائمة أيضاً.",
  "urun.tumunuGoster": "عرض كل الأصناف ({adet})",

  "tesekkur.googleBaslik": "شكراً جزيلاً! 🎉",
  "tesekkur.googleMetin":
    "سعدنا بإعجابك. مشاركة هذه التجربة على Google تعني لنا الكثير — لن تستغرق أكثر من ٣٠ ثانية.",
  "tesekkur.googleButon": "اكتب تقييماً على Google",
  "tesekkur.googleAtla": "يمكنك تخطي هذه الخطوة إن أردت.",
  "tesekkur.icBaslik": "شكراً على ملاحظاتك",
  "tesekkur.icMetin":
    "وصلت رسالتك مباشرة إلى مسؤول المكان. شكراً لإخبارنا بما كان ناقصاً — سنعالج الأمر في أقرب وقت.",

  "kvkk.ozet":
    "لقد قرأت إشعار الخصوصية. إذا تركت بيانات تواصل، فإنني أوافق صراحةً على مشاركتها مع {ad} وحفظها لمدة {gun} يوماً للرد على هذه الملاحظة فقط.",
  "kvkk.baslik": "إشعار حماية البيانات الشخصية",
  "kvkk.sorumluBaslik": "المسؤول عن البيانات",
  "kvkk.veriBaslik": "ما الذي نجمعه",
  "kvkk.veriMetin":
    "التقييمات والتعليق الذي تكتبه. واختيارياً رقم الهاتف أو البريد الإلكتروني الذي تتركه لنتمكن من الرد عليك. لا نطلب اسمك.",
  "kvkk.amacBaslik": "لماذا",
  "kvkk.amacMetin":
    "تُستخدم التقييمات والتعليقات لقياس جودة خدمتنا؛ وتُستخدم بيانات التواصل للرد على هذه الملاحظة فقط. لا تُستخدم للتسويق ولا تُشارك مع أطراف ثالثة.",
  "kvkk.dayanakBaslik": "الأساس القانوني",
  "kvkk.dayanakMetin":
    "تُعالج التقييمات والتعليقات في إطار مصلحتنا المشروعة في تحسين الخدمة. أما بيانات التواصل فتُحفظ بموافقتك الصريحة فقط — وإن تركتها فارغة تُسجَّل ملاحظتك على أي حال.",
  "kvkk.sureBaslik": "مدة الحفظ",
  "kvkk.sureMetin":
    "تُحفظ بيانات التواصل مدة {gun} يوماً كحد أقصى ثم تُحذف تلقائياً. أما التقييمات والتعليقات فتبقى لأغراض إحصائية دون ربطها بهويتك.",
  "kvkk.haklarBaslik": "حقوقك",
  "kvkk.haklarMetin":
    "يحق لك الاطلاع على بياناتك وطلب تصحيحها أو حذفها وسحب موافقتك. يكفي التواصل مع المكان؛ وتُحذف بيانات تواصلك فوراً عند الطلب.",
  "kvkk.asilDil": "هذه ترجمة للتسهيل. النص التركي هو النص الملزم قانوناً.",

  "secenek.tuvaletler": "دورات المياه",
  "secenek.masalar": "الطاولات",
  "secenek.zemin": "الأرضية",
  "secenek.catalBicak": "أدوات المائدة",
  "secenek.bardaklar": "الأكواب",
  "secenek.cokBeklettiler": "انتظرت طويلاً",
  "secenek.ilgisizdi": "لم يهتموا",
  "secenek.siparisYanlis": "الطلب كان خاطئاً",
  "secenek.uslupKotu": "الأسلوب كان سيئاً",
  "secenek.soguktu": "كان بارداً",
  "secenek.tuzBaharat": "الملح/التوابل",
  "secenek.porsiyonKucuk": "الحصة صغيرة",
  "secenek.tazelik": "الطزاجة",
  "secenek.sunum": "التقديم",
  "secenek.siparisAlinmasi": "أخذ الطلب",
  "secenek.yemeginGelmesi": "وصول الطعام",
  "secenek.hesapOdemesi": "دفع الحساب",
  "secenek.porsiyonaGorePahali": "غالٍ مقابل الحصة",
  "secenek.menuFiyatFarkli": "السعر يختلف عن القائمة",
  "secenek.servisUcreti": "رسوم الخدمة",
  "secenek.gurultu": "الضجيج",
  "secenek.muzikSesi": "صوت الموسيقى",
  "secenek.isiHavalandirma": "الحرارة/التهوية",
  "secenek.aydinlatma": "الإضاءة",
  "secenek.koltuklar": "المقاعد",
  "secenek.tabakDuzeni": "ترتيب الطبق",
  "secenek.sicaklik": "درجة الحرارة",
  "secenek.porsiyonGorunumu": "مظهر الحصة",
  "secenek.temizlik": "النظافة",
  "secenek.kagitSabunYok": "لا يوجد ورق/صابون",
  "secenek.koku": "الرائحة",
  "secenek.siraBekledim": "انتظرت في الطابور",
  "secenek.yerYoktu": "لا توجد أماكن",
  "secenek.uzunBekledim": "انتظرت طويلاً",
  "secenek.ucret": "الرسوم",
  "gorsel.sec": "اختر صورة",
  "gorsel.degistir": "تغيير",
  "gorsel.kaldir": "إزالة",
  "gorsel.isleniyor": "جارٍ المعالجة…",
  "gorsel.hataTur": "يرجى اختيار ملف صورة.",
  "gorsel.hataIsleme": "تعذّرت معالجة الصورة. جرّب ملفاً آخر.",
  "gorsel.hataBoyut": "الملف كبير جداً (الحد الأقصى {boyut}). جرّب صورة أصغر.",
  "iys.metin":
    "أوافق على تلقي رسائل إلكترونية تجارية تتضمن حملات وخصومات وإعلانات من {ad} عبر {kanal} على عنوان التواصل الذي تركته. ويمكنني سحب هذه الموافقة مجاناً في أي وقت.",
  "iys.ipucu": "اختياري. تُسجَّل ملاحظتك في كل الأحوال.",
  "iys.metniOku": "اقرأ إشعار الخصوصية",
  "iys.sms": "رسالة نصية",
  "iys.eposta": "البريد الإلكتروني",
};

const ru: Sozluk = {
  "dil.sec": "Язык",
  "ortak.masa": "Стол {no}",
  "ortak.giris": "Вход",
  "ortak.hosGeldiniz": "Добро пожаловать",
  "ortak.menu": "Меню",
  "ortak.kapat": "Закрыть",
  "ortak.istegeBagli": "(необязательно)",

  "karsilama.menuBaslik": "Посмотреть меню",
  "karsilama.menuAciklama": "Фото, цены и что есть сегодня",
  "karsilama.anketBaslik": "Оцените ваш визит",
  "karsilama.anketAciklama": "Займёт 30 секунд",
  "karsilama.dipnot": "Ваш отзыв попадёт напрямую к владельцу.",
  "duyurular.baslik": "Объявления",
  "duyurular.geriDon": "← Назад",
  "duyurular.bosDurum": "Сейчас нет активных объявлений.",
  "siparis.baslik": "Заказ онлайн",
  "menu.fiyatGuncelleme": "Цены обновлены {tarih}.",

  "iletisim.instagram": "Instagram",
  "iletisim.wifiButon": "Данные Wi-Fi",
  "iletisim.wifiAgi": "Сеть Wi-Fi",
  "iletisim.wifiSifre": "Пароль",
  "iletisim.kopyala": "Копировать",
  "iletisim.kopyalandi": "Скопировано",

  "menu.ara": "Поиск по меню…",
  "menu.aramaEtiket": "Поиск по меню",
  "menu.filtreler": "Фильтры по диете и аллергенам",
  "menu.bolumler": "Разделы меню",
  "menu.tumBolumler": "Меню",
  "menu.urunAdedi": "{adet} позиций",
  "menu.sonucSayisi": "Найдено блюд: {adet}",
  "menu.temizle": "Сбросить",
  "menu.aramaBos": "По запросу «{terim}» ничего не найдено.",
  "menu.filtreBos": "Нет блюд, подходящих под выбранные фильтры.",
  "menu.bugunYok": "Закончилось",
  "menu.ayrinti": "{ad} — подробнее",
  "menu.secimEkle": "{ad} — добавить в отзыв",
  "menu.fiyat": "Цена",
  "menu.anketKisayolBaslik": "Оцените ваш визит",
  "menu.anketKisayolAciklama": "Можно оценить каждое блюдо отдельно",
  "menu.kdv": "Цены включают НДС. Меню обновляет заведение.",
  "menu.sikayetOneri": "Жалобы и предложения",
  "menu.secimAltBaslik": "Отметьте, что заказывали",
  "menu.secimBaslik": "Что вы заказывали?",
  "menu.secimAciklama": "Отметьте, что вы ели, затем добавьте это в отзыв ниже.",
  "menu.secilenSayisi": "Выбрано блюд: {adet}",
  "menu.secimYok": "Пока ничего не выбрано",
  "menu.secimTamamla": "Добавить в отзыв",
  "menu.secimBos": "Вернуться к отзыву",
  "menu.secimdenCikar": "Убрать из выбора",

  "etiket.vegan": "Веганское",
  "etiket.vejetaryen": "Вегетарианское",
  "etiket.glutensiz": "Без глютена",
  "etiket.laktozsuz": "Без лактозы",
  "etiket.aci": "Острое",
  "etiket.yeni": "Новинка",
  "etiket.populer": "Популярное",

  "yildiz.1": "Очень плохо",
  "yildiz.2": "Плохо",
  "yildiz.3": "Нормально",
  "yildiz.4": "Хорошо",
  "yildiz.5": "Отлично",
  "yildiz.etiket": "{sayi} звёзд — {ad}",
  "yildiz.genel": "Общая оценка",
  "yildiz.kategori": "Оценка: {ad}",

  "anket.baslik": "Как вам у нас?",
  "anket.menuyeDon": "Назад к меню",
  "anket.ipucu": "Нажмите на звезду, чтобы оценить",
  "anket.altBilgi1": "Ваш отзыв попадёт напрямую к управляющему {ad}.",
  "anket.altBilgi2": "Имя мы не спрашиваем — можно остаться анонимным.",
  "anket.detaylar": "Подробнее",
  "anket.detayIpucu": "Любой пункт можно пропустить.",
  "anket.sorunSoru": "С чем именно возникла проблема?",
  "anket.yorumBaslik": "Хотите что-то добавить?",
  "anket.yorumDusuk": "Что пошло не так? Напишите, и мы это исправим.",
  "anket.yorumYuksek": "Что понравилось или что можно улучшить...",
  "anket.fotoBaslik": "Хотите добавить фото? (необязательно)",
  "anket.fotoIpucu": "Его увидит только управляющий.",
  "anket.iletisimBaslik": "Хотите, чтобы мы с вами связались?",
  "anket.iletisimDusuk": "Оставьте контакт — управляющий свяжется с вами лично.",
  "anket.iletisimYuksek": "Свяжемся только по поводу этого отзыва.",
  "anket.iletisimKampanyaBaslik": "Хотите узнавать об акциях?",
  "anket.iletisimKampanyaMetin":
    "Оставьте контакты — вы первыми узнаете о новинках и акциях.",
  "anket.iletisimKanali": "Способ связи",
  "anket.telefon": "Телефон",
  "anket.eposta": "Эл. почта",
  "anket.telefonOrnek": "05XX XXX XX XX",
  "anket.epostaOrnek": "name@example.com",
  "anket.gonder": "Отправить",
  "anket.gonderiliyor": "Отправляем…",
  "anket.googleButon": "Оценить на Google",
  "anket.puanGerekli": "Сначала поставьте общую оценку.",
  "anket.besYildizBaslik": "Вы поставили нам 5 звёзд, спасибо! 🎉",
  "anket.besYildizMetin":
    "Не могли бы вы уделить пару секунд, чтобы оставить отзыв и на Google? Перед этим вы можете по желанию оставить свои контактные данные, чтобы мы могли с вами связаться.",
  "anket.rizaGerekli":
    "Чтобы оставить контакты, примите уведомление о конфиденциальности.",

  "urun.baslik": "Что вы заказывали?",
  "urun.aciklama": "Можно оценить каждое блюдо отдельно. Необязательно.",
  "urun.menudenSec": "Выбрать из меню",
  "urun.menudenSecAciklama": "Отметьте в меню с фото и вернитесь сюда",
  "urun.ara": "Поиск блюда...",
  "urun.bulunamadi": "Блюда с таким названием нет. Можно выбрать его из меню.",
  "urun.tumunuGoster": "Показать все блюда ({adet})",

  "tesekkur.googleBaslik": "Большое спасибо! 🎉",
  "tesekkur.googleMetin":
    "Рады, что вам понравилось. Отзыв на Google очень нам поможет — это займёт 30 секунд.",
  "tesekkur.googleButon": "Оставить отзыв в Google",
  "tesekkur.googleAtla": "Этот шаг можно пропустить.",
  "tesekkur.icBaslik": "Спасибо за отзыв",
  "tesekkur.icMetin":
    "Ваше сообщение получил управляющий заведением. Спасибо, что рассказали о недостатках — мы разберёмся в ближайшее время.",

  "kvkk.ozet":
    "Я прочитал(а) уведомление о конфиденциальности. Если я оставлю контактные данные, я даю явное согласие на их передачу {ad} и хранение в течение {gun} дней исключительно для ответа на этот отзыв.",
  "kvkk.baslik": "Уведомление о защите персональных данных",
  "kvkk.sorumluBaslik": "Оператор данных",
  "kvkk.veriBaslik": "Какие данные мы собираем",
  "kvkk.veriMetin":
    "Ваши оценки и комментарий. По желанию — номер телефона или адрес эл. почты, чтобы мы могли ответить. Имя мы не спрашиваем.",
  "kvkk.amacBaslik": "Зачем",
  "kvkk.amacMetin":
    "Оценки и комментарии нужны для измерения качества обслуживания; контактные данные используются только для ответа на этот отзыв. Они не используются в маркетинге и не передаются третьим лицам.",
  "kvkk.dayanakBaslik": "Правовое основание",
  "kvkk.dayanakMetin":
    "Оценки и комментарии обрабатываются в рамках нашего законного интереса в улучшении сервиса. Контактные данные хранятся только с вашего явного согласия — если не указывать их, отзыв всё равно будет записан.",
  "kvkk.sureBaslik": "Срок хранения",
  "kvkk.sureMetin":
    "Контактные данные хранятся не более {gun} дней и затем удаляются автоматически. Оценки и комментарии хранятся дальше для статистики, без привязки к вашей личности.",
  "kvkk.haklarBaslik": "Ваши права",
  "kvkk.haklarMetin":
    "Вы вправе получить доступ к своим данным, потребовать их исправления или удаления и отозвать согласие. Достаточно обратиться в заведение; контактные данные удаляются немедленно по требованию.",
  "kvkk.asilDil":
    "Это перевод для удобства. Юридически обязательным является текст на турецком языке.",

  "secenek.tuvaletler": "Туалеты",
  "secenek.masalar": "Столы",
  "secenek.zemin": "Пол",
  "secenek.catalBicak": "Приборы",
  "secenek.bardaklar": "Посуда",
  "secenek.cokBeklettiler": "Долго ждали",
  "secenek.ilgisizdi": "Невнимательны",
  "secenek.siparisYanlis": "Заказ перепутали",
  "secenek.uslupKotu": "Грубое обращение",
  "secenek.soguktu": "Было холодным",
  "secenek.tuzBaharat": "Соль/специи",
  "secenek.porsiyonKucuk": "Маленькая порция",
  "secenek.tazelik": "Свежесть",
  "secenek.sunum": "Подача",
  "secenek.siparisAlinmasi": "Приём заказа",
  "secenek.yemeginGelmesi": "Подача блюд",
  "secenek.hesapOdemesi": "Оплата счёта",
  "secenek.porsiyonaGorePahali": "Дорого за порцию",
  "secenek.menuFiyatFarkli": "Цена не как в меню",
  "secenek.servisUcreti": "Плата за обслуживание",
  "secenek.gurultu": "Шум",
  "secenek.muzikSesi": "Громкость музыки",
  "secenek.isiHavalandirma": "Температура/вентиляция",
  "secenek.aydinlatma": "Освещение",
  "secenek.koltuklar": "Сиденья",
  "secenek.tabakDuzeni": "Оформление блюда",
  "secenek.sicaklik": "Температура",
  "secenek.porsiyonGorunumu": "Вид порции",
  "secenek.temizlik": "Чистота",
  "secenek.kagitSabunYok": "Нет бумаги/мыла",
  "secenek.koku": "Запах",
  "secenek.siraBekledim": "Была очередь",
  "secenek.yerYoktu": "Не было мест",
  "secenek.uzunBekledim": "Долго ждал",
  "secenek.ucret": "Стоимость",
  "gorsel.sec": "Выбрать фото",
  "gorsel.degistir": "Заменить",
  "gorsel.kaldir": "Убрать",
  "gorsel.isleniyor": "Обработка…",
  "gorsel.hataTur": "Выберите файл изображения.",
  "gorsel.hataIsleme": "Не удалось обработать изображение. Попробуйте другой файл.",
  "gorsel.hataBoyut": "Файл слишком большой (макс. {boyut}). Попробуйте изображение поменьше.",
  "iys.metin":
    "Я согласен(на) получать коммерческие электронные сообщения с акциями, скидками и анонсами от {ad} через {kanal} на оставленный мной контакт. Я могу отозвать это согласие бесплатно в любой момент.",
  "iys.ipucu": "Необязательно. Отзыв будет сохранён в любом случае.",
  "iys.metniOku": "Прочитать уведомление",
  "iys.sms": "SMS",
  "iys.eposta": "эл. почту",
};

const SOZLUKLER: Record<Dil, Sozluk> = { tr, en, ar, ru };

/**
 * Metni seçili dilde döndürür.
 *
 * Çeviri boşsa (ör. Türkçede gösterilmeyen "asıl dil" notu) boş dize döner
 * ve çağıran taraf o satırı hiç çizmez.
 */
export function cevir(
  dil: Dil,
  anahtar: MetinAnahtari,
  degiskenler?: Record<string, string | number>,
): string {
  const sozluk = SOZLUKLER[dil] ?? SOZLUKLER[VARSAYILAN_DIL];
  const kalip = sozluk[anahtar] ?? SOZLUKLER[VARSAYILAN_DIL][anahtar];
  if (!degiskenler) return kalip;
  return kalip.replace(/\{(\w+)\}/g, (tam, ad: string) =>
    ad in degiskenler ? String(degiskenler[ad]) : tam,
  );
}
