// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migration'lar HAVUZSUZ bağlantıdan geçer: PgBouncer işlem kipinde
    // çalışıyor ve migration'ların ihtiyaç duyduğu oturum düzeyi
    // komutlarını (advisory lock, CREATE TYPE) desteklemiyor. Çalışma
    // zamanı ise DATABASE_URL ile pooler'a bağlanır (bkz. lib/cekirdek/db.ts).
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
